apiVersion: v1
kind: Service
metadata:
  name: reyankrish-preview
  namespace: demo

spec:
  type: ClusterIP
  selector:
    app: reyankrish-app

  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
